### ISSUE TITLE
Docker image with Elixir 1.1.x

### ISSUE THREAD

**Issue by kazuhiro** [asaaki/mix-edip#7]
Is there any chance to see mix-edip using a docker image with elixir 1.1.x in near future? :)

**Comment by asaaki** [comment]
I released v0.4.3, which uses updated EDIP tool (0.4.4) for _Elixir 1.1.1_.

Give it a try and tell me if it works for you.

**Comment by kazuhiro** [comment]
It's working! Thx for help :)

**Comment by asaaki** [comment]
Sounds great!
Thank you for confirmation.
